import type { Metadata } from 'next';
import { Figtree, JetBrains_Mono } from 'next/font/google';
import { Header } from '@/components/header';
import { ThemeProvider } from './_provider/next-themes';
import './globals.css';

const figtree = Figtree({
  variable: '--font-figtree',
  subsets: ['latin'],
});

const jetBrainsMono = JetBrains_Mono({
  variable: '--font-jetbrains-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${figtree.className} ${jetBrainsMono.variable} relative min-h-screen w-full p-2 antialiased dark:bg-radial dark:from-neutral-800 dark:to-neutral-900`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          disableTransitionOnChange
          enableSystem
        >
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
